
# Default settings for the command string sent to the PDiag distributor

---
Kennung: 03
Ini Datei: testini
Szenario: testscenario
Param1: j
Param2: j
Param3: j
Param4: j
Param5: j
Param6: j
         
